/**
 * DecisionNarrative — LLM-generated explanation for a canonical decision.
 *
 * ⚠️  Presentational ONLY. The narrative text comes verbatim from the backend.
 *     Paragraphs are separated by blank lines.
 */
import { useCanonicalNarrative } from "../../hooks/useCanonicalNarrative";

interface DecisionNarrativeProps {
  pair: string;
  horizonDays?: number;
}

export function DecisionNarrative({
  pair,
  horizonDays = 5,
}: DecisionNarrativeProps): JSX.Element {
  const { data, isLoading, isError } = useCanonicalNarrative(
    pair,
    horizonDays
  );

  if (isLoading) {
    return (
      <div className="rounded-xl border border-line bg-panel-2 p-6">
        <div className="text-xs uppercase tracking-wider text-muted mb-3">
          📖 What this means
        </div>
        <div className="space-y-2">
          <div className="h-4 bg-panel rounded animate-pulse" />
          <div className="h-4 bg-panel rounded animate-pulse w-5/6" />
          <div className="h-4 bg-panel rounded animate-pulse w-4/6" />
        </div>
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className="rounded-xl border border-line bg-panel-2 p-6">
        <div className="text-xs uppercase tracking-wider text-muted mb-3">
          📖 What this means
        </div>
        <div className="text-sm text-muted italic">
          Narrative unavailable for {pair}.
        </div>
      </div>
    );
  }

  const paragraphs = data.narrative
    .split("\n\n")
    .map((p) => p.trim())
    .filter(Boolean);

  const timestamp = data.generated_at
    ? new Date(data.generated_at).toLocaleString()
    : null;

  return (
    <div className="rounded-xl border border-line bg-panel-2 p-6">
      <div className="flex items-center justify-between mb-3">
        <div className="text-xs uppercase tracking-wider text-muted">
          📖 What this means
        </div>
        {data.cache?.hit && (
          <span className="text-[10px] uppercase tracking-wider text-muted bg-panel px-2 py-0.5 rounded">
            cached
          </span>
        )}
      </div>

      <div className="space-y-3 text-sm text-ink-soft leading-relaxed">
        {paragraphs.map((paragraph, idx) => (
          <p key={idx}>{paragraph}</p>
        ))}
      </div>

      <div className="mt-4 pt-3 border-t border-line text-[11px] text-muted font-mono">
        Generated by {data.provider} · {data.model}
        {timestamp && ` · ${timestamp}`}
        {data.served_count > 1 && ` · served ${data.served_count}×`}
      </div>
    </div>
  );
}
