services:
  - type: web
    name: MeridianFX
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FRED_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false
      - key: TWELVE_DATA_KEY
        sync: false
    healthCheckPath: /health
